# Created by pyp2rpm-3.1.3
%global pypi_name intervaltree

Name:           python-%{pypi_name}
Version:        2.1.0
Release:        1%{?dist}
Summary:        Editable interval tree data structure for Python 2 and 3

License:        Apache License, Version 2.0
URL:            https://github.com/chaimleib/intervaltree
Source0:        https://files.pythonhosted.org/packages/source/i/%{pypi_name}/%{pypi_name}-%{version}.tar.gz
BuildArch:      noarch
 
BuildRequires:  python-setuptools
BuildRequires:  python2-devel
BuildRequires:  python-pytest
 
BuildRequires:  python3-setuptools
BuildRequires:  python3-devel
BuildRequires:  python3-pytest

%description
.. This file is automatically generated by setup.py from README.md and
CHANGELOG.md.intervaltree A mutable, selfbalancing interval tree for Python 2
and 3. Queries may be by point, by range overlap, or by range envelopment.This
library was designed to allow tagging text and time intervals, where the
intervals include the lower bound but not the upper bound.Installing .. code::
sh pip install ...

%package -n     python2-%{pypi_name}
Summary:        Editable interval tree data structure for Python 2 and 3
%{?python_provide:%python_provide python2-%{pypi_name}}
 
Requires:       python-sortedcontainers
%description -n python2-%{pypi_name}
.. This file is automatically generated by setup.py from README.md and
CHANGELOG.md.intervaltree A mutable, selfbalancing interval tree for Python 2
and 3. Queries may be by point, by range overlap, or by range envelopment.This
library was designed to allow tagging text and time intervals, where the
intervals include the lower bound but not the upper bound.Installing .. code::
sh pip install ...

%package -n     python3-%{pypi_name}
Summary:        Editable interval tree data structure for Python 2 and 3
%{?python_provide:%python_provide python3-%{pypi_name}}
 
Requires:       python3-sortedcontainers
%description -n python3-%{pypi_name}
.. This file is automatically generated by setup.py from README.md and
CHANGELOG.md.intervaltree A mutable, selfbalancing interval tree for Python 2
and 3. Queries may be by point, by range overlap, or by range envelopment.This
library was designed to allow tagging text and time intervals, where the
intervals include the lower bound but not the upper bound.Installing .. code::
sh pip install ...


%prep
%autosetup -n %{pypi_name}-%{version}
# Remove bundled egg-info
rm -rf %{pypi_name}.egg-info

%build
%py2_build
%py3_build

%install
# Must do the subpackages' install first because the scripts in /usr/bin are
# overwritten with every setup.py install.
%py3_install

%py2_install


%files -n python2-%{pypi_name}
%license LICENSE.txt
%doc README.md README.rst
%{python2_sitelib}/%{pypi_name}
%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info

%files -n python3-%{pypi_name}
%license LICENSE.txt
%doc README.md README.rst
%{python3_sitelib}/%{pypi_name}
%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info

%changelog
* Thu Nov 17 2016 David Goerger - 2.1.0-1
- Initial package.